name: memoryCash CI

on:
  push:
    branches: [ http-start ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: go.sum

      - name: Setup dependencies
        run: go mod download && go mod verify

      - name: Run tests
        run: |
          cd MemoryCash
          go test -v -race -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Install golangci-lint
        run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin

      - name: Linting
        working-directory: ./MemoryCash
        run: |
          # Используем локально установленный golangci-lint
          ../bin/golangci-lint run ./...

      - name: Run go vet
        run: cd MemoryCash && go vet ./...

      - name: Security scan
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          cd MemoryCash && govulncheck ./...
